//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointOfSalesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public string name { get; set; }
        public string username { get; set; }
        public string userPassword { get; set; }
        public string designation { get; set; }
        public string contact { get; set; }
        public string email { get; set; }
        public Nullable<int> birthdate { get; set; }
        public Nullable<int> age { get; set; }
        public string emergencyContact { get; set; }
        public string emergencycontactNum { get; set; }
        public string userImage { get; set; }
    }
}
